### ISSUE TITLE
Github Releases

### ISSUE THREAD

**Issue by vaporup** [nspawn/nspawn#15]
Currently I package the scripts for my own APT repo and use a date for the package version.
Today I only saw by accident that a new version was pushed f390e7495109a9c4caccd01492839443ec7364f3

It would be great if you could create a Github Release which can easier be monitored (nvchecker)
and packaged.

**Comment by Edu4rdSHL** [comment]
Hello, @vaporup, I will create releases from now.

Edit: 0.4 released - https://github.com/nspawn/nspawn/releases/tag/0.4
